### ISSUE TITLE
Storage Terminals always cause a PacketCodecException in ATM 8 latest update (v1.1.0)

### ISSUE THREAD

**Issue by flann** [CyclopsMC/IntegratedTerminals#116] opened 2023-12-25 14:05 UTC
#### Issue type:

- :bug: Bug 

____

#### Short description:

Attempting to access any storage terminal always causes a PacketCodecException. This only happens client-side. There's nothing in the server logs other than showing that the user disconnected.

#### Steps to reproduce the problem:

1. Connect a storage terminal to an inventory.
2. Right-click the terminal
3. Client disconnects from the server with a "PacketCodecException". Log trace shows the dreaded "io.netty.handler.codec.EncoderException: java.io.EOFException: fieldSize is too long! Length is 28009, but maximum is 45"

#### Expected behaviour:

The storage terminal should open and display the contents of the inventory.

____

#### Versions:

- This mod: IntegratedTerminals-1.19.2-1.4.11
- Minecraft: 1.19.2
- Forge: 43.2.14

#### Log file:

https://gist.github.com/flann/00549bf494d38454a8ede9e7dd685747#file-latest-log

**Comment by rubensworks** [comment] 2023-12-25 14:05
Thanks for reporting!

**Comment by rubensworks** [comment] 2023-12-25 14:20
This seems to be a duplicate of #112.

Please try lowering `terminalStoragePacketMaxRecipes` and/or `terminalStoragePacketMaxInstances` in your config.

Should that not fix the problem, please let me know.

**Closed as completed by rubensworks** 2023-12-25 14:20 UTC
Labels: bug, mc-1.19
