### ISSUE TITLE
terminal settings are persistent to a save

### ISSUE THREAD

**Issue by antrobot1234** [CyclopsMC/IntegratedTerminals#54] opened 2020-04-26 22:04 UTC
#### Issue type:

- :heavy_plus_sign: Feature request

____

#### Short description:

terminal settings (such as which storage is selected and sorting options) should be saved per-player and per-world so when you save and quit, it isn't reset.

**Comment by rubensworks** [comment] 2020-04-27 06:53
Duplicate of #28.

**Closed as completed by rubensworks** 2020-04-27 06:53 UTC
