### ISSUE TITLE
unable to auto complete certain recipes from jei even though the items are in the system

### ISSUE THREAD

**Issue by Fedwick** [CyclopsMC/IntegratedTerminals#31] opened 2019-04-25 22:11 UTC
#### Issue type:

auto complete certain recipes from jei

#### Short description:

unable to pull certain recipes from jei even though the items are in the system

#### Steps to reproduce the problem:

i will give 1 item as an example, the world block exporter

1. get a container with an item interface and a storage terminal
2. place an item exporter, a logic director and a diamond pick in your system
3. open your storage terminal and click the world block exporter from jei and then click the +sign to pull the recipe in your monitors crafting grid (it does not recognize the pick)

#### Expected behaviour:
it should auto complete the recipe because you have a diamond pick in your system

#### Versions:

- IntegratedTerminals-1.12.2-1.0.6
- Minecraft 1.12.2
- Forge 14.23.5.2781

**Comment by rubensworks** [comment] 2019-04-26 06:12
Does the pick have damage on it? Does this happen for all recipes, or only recipes with damageable items?

**Comment by Fedwick** [comment] 2019-04-26 10:10
i will try to give you a few items, this is my test pack
most of the recipes work ok ! there are a few items that don't work, maybe it has something to do with NBT or damage ? my programming experience in MC is almost 0 though so i don't know.

this is a basic storage system
![2019-04-26_12 18 49](https://user-images.githubusercontent.com/24882575/56797573-a8fcf080-681d-11e9-801d-b9fa1ca50f8a.png)

all the indigence for world block exporter are inside and the pick is fresh
![2019-04-26_12 19 07](https://user-images.githubusercontent.com/24882575/56797585-ae5a3b00-681d-11e9-915d-6c3dd15d0b99.png)

i am unable to autocomplete
![2019-04-26_12 19 25](https://user-images.githubusercontent.com/24882575/56797587-af8b6800-681d-11e9-9c50-924bbd232030.png)

now i will try a recipe from blood magic, all the items are in the system but i am unable to autocomplete
the blood orb is in the system though !
![2019-04-26_12 24 46](https://user-images.githubusercontent.com/24882575/56797891-6a1b6a80-681e-11e9-9d47-b1fcd368861c.png)

ok now i switch to enigmatica 2 expert pack ( the pack only had tunnels and dynamics so i manually add integrated terminals )

i wanna craft energy interfaces all the items are in my system
![2019-04-26_12 55 57](https://user-images.githubusercontent.com/24882575/56800105-f0d24680-6822-11e9-898a-6aba5b1fa4a7.png)

but i am unable to auto complete

![2019-04-26_12 56 10](https://user-images.githubusercontent.com/24882575/56800168-13fcf600-6823-11e9-987c-eec588613239.png)

here i try to craft the automatic squeezer and it recognizes the batteries and the squeezers, but it does not recognize a squeezer that was placed and later picked up ! maybe something changed in the items NBT ? this recipe is changed by enigmatica but i think that's irrelevant. (the second obsidian plate in not in my system)

![2019-04-26_13 05 33](https://user-images.githubusercontent.com/24882575/56800570-01cf8780-6824-11e9-9670-9efe5b5f545e.png)

I can give you more examples as i find them thank you for your work !

**Comment by rubensworks** [comment] 2019-04-26 10:12
Interesting, thanks for the info, will look into it.

**Comment by rubensworks** [comment] 2019-05-03 15:25
It looks like this was caused by the same problem as in https://github.com/CyclopsMC/IntegratedCrafting/issues/17 when Astral Sorcery was installed. This has been fixed in CommonCapabilities 2.2.1.

**Comment by Fedwick** [comment] 2019-05-03 23:53
I installed CommonCapabilities 2.2.1 thanks for the fix ! i also found out that autocomplete isn't working with a bound orb from blood magic even after the fix . (very minor issue but everybody is using bound orbs) anyway if you keep an unbound orb in your system autocomplete works !

unbound orb
![2019-05-04_01 57 23](https://user-images.githubusercontent.com/24882575/57169735-3a1d2a00-6e11-11e9-8719-9456e0be3268.png)

bound orb, my name is in the nbt + numbers ?
![2019-05-04_01 57 32](https://user-images.githubusercontent.com/24882575/57169737-3d181a80-6e11-11e9-8f3d-9a181c614fb7.png)

binding nbt tag
![2019-05-04_02 39 44](https://user-images.githubusercontent.com/24882575/57170581-7606be00-6e16-11e9-905d-36f01a3a3a69.png)

id nbt tag
![2019-05-04_02 51 16](https://user-images.githubusercontent.com/24882575/57170734-984d0b80-6e17-11e9-8b82-221e938f10cc.png)

If i find any items from any other mods that don't autocomplete i will let you know !
sorry if this is re-opening the issue.

**Comment by rubensworks** [comment] 2019-05-04 07:03
Hmm, that won't be an easy one to fix. Will look into it later.

**Comment by rubensworks** [comment] 2019-05-19 13:22
@Fedwick I just thought of something that may already be able to fix your issue.

Could you try adding the following entry into the CommonCapabilities config file entry for `ignoreNbtPathsForEqualityFilters`: `"$.binding"` ?

If this solves your problem, I can add it to the default config.

**Comment by Fedwick** [comment] 2019-05-20 20:58
it works !

would it be possible to make a config like that to ignore item damage ? it would help with recipes from IC2 with items that require energy i think. they auto complete only when full.

**Comment by rubensworks** [comment] 2019-05-21 06:21
Note to self: add this to the default config.

@Fedwick The item damage thing would be a completely different thing that would require quite some work, could you create a separate issue for that?

**Closed as completed** 2019-05-21 14:57 UTC
Labels: bug
